version: "3"

dotenv:
  - .env
  - .env.local

env:
  PORT: 8080

vars:
  container_name: app
  container_tag: latest

tasks:
  dev:
    run: always
    cmds:
      - air

  build:
    deps:
      - task: generate
    cmds:
      - CGO_ENABLED=0 go build -o build/server ./src/main.go

  container:
    deps:
      - task: generate
    cmds:
      - docker build -t {{.container_name}}:{{.container_tag}} .

  generate:
    aliases:
      - gen
      - g
    generates:
      - src/templates/**/*.go
      - src/views/**/*.go
      - src/static/dist/**/*.css
      - src/static/dist/**/*.js
    sources:
      - src/templates/**/*.templ
      - src/views/**/*.templ
      - tailwind.config.js
      - src/styles/css/global.css
      - src/static/js/**/*.js
    cmds:
      - bunx tailwindcss build -i ./src/static/css/global.css -o ./src/static/dist/style.css
      - bun build src/static/js/index.js --outfile=src/static/dist/bundle.js --minify
      - go run github.com/a-h/templ/cmd/templ@latest generate
      - go generate ./src/...
